// <auto-generated />
using FPSOManagerApi_CS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FPSOManagerApi_CS.Migrations
{
    [DbContext(typeof(FPSODbContext))]
    [Migration("20201011011143_initDb")]
    partial class initDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("FPSOManagerApi_CS.Models.Equipment", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vesselcode")
                        .HasColumnType("TEXT");

                    b.Property<bool>("active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("location")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("code");

                    b.HasIndex("Vesselcode");

                    b.ToTable("equipment");
                });

            modelBuilder.Entity("FPSOManagerApi_CS.Models.Vessel", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("TEXT");

                    b.HasKey("code");

                    b.ToTable("vessels");
                });

            modelBuilder.Entity("FPSOManagerApi_CS.Models.Equipment", b =>
                {
                    b.HasOne("FPSOManagerApi_CS.Models.Vessel", null)
                        .WithMany("equipments")
                        .HasForeignKey("Vesselcode");
                });
#pragma warning restore 612, 618
        }
    }
}
